mybot:
  # Publish all joint states -----------------------------------
  /gripper/joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Tips Effort Controllers ---------------------------------------
  /gripper/lefttip_effort_controller:
    type: effort_controllers/JointEffortController
    joint: ur5_arm_gripper_link_2_left_tip_joint
    pid: {p: 100.0, i: 0.1, d: 10.0}
  /gripper/righttip_effort_controller:
    type: effort_controllers/JointEffortController
    joint: ur5_arm_gripper_link_2_right_tip_joint
    pid: {p: 100.0, i: 0.1, d: 10.0}

